name: build-and-run-aoc-solution
on: 
  push:
    paths:
      - '.github/workflows/build_solution.yml'
      - 'solutions/day01/**'
      - 'solutions/day02/**'
      - 'solutions/day03/**'
  workflow_dispatch:
jobs:
  build-solution:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        directory: [ 'solutions/day01'
                   , 'solutions/day02'
                   , 'solutions/day03'
                   ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: debug event payload
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Determine Changed Directory
        run: |
          # Get the SHA of the previous commit
          PREV_COMMIT_SHA=$(git log --pretty=%H --skip 1 -n 1 ${{ github.sha }})

          # Get the list of changed files between the previous and current commit
          CHANGED_FILES=$(git diff --name-only ${{ github.sha }} $PREV_COMMIT_SHA)

          # Extract the directory name of the first changed file in the specified directories
          CHANGED_DIRECTORIES=$(echo "$CHANGED_FILES" | grep -o '^solutions/day[0-9]\{1,2\}')

          echo "$CHANGED_FILES"
          echo "$CHANGED_DIRECTORIES"

      - name: update stack
        run: stack upgrade
      - name: print stack version
        run: stack --version
      - name: build and run solution
        run: cd ${{ matrix.directory }} && stack build
