name: build-and-run-aoc-solution
on: 
  workflow_dispatch:
  push:
    - 'solutions/day01'
    - 'solutions/day02'
    - 'solutions/day03'
jobs:
  build-and-run:
    runs-on: ubuntu-22.04
    steps:
      - name: update stack
    strategy:
      matrix:
        directory: [ 'solutions/day01'
                   , 'solutions/day02'
                   , 'solutions/day03'
                   ]
        run: stack upgrade
      - name: print stack version
        run: stack --version
      - name: checkout solutions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ matrix.directory  }}
      - name: build and run solution
        run: cd ${{ matrix.directory }} && stack build
