name: Build Solutions
on: 
  push:
    paths:
      - '.github/workflows/build_solution.yml'
      - 'solutions/day01/**'
      - 'solutions/day02/**'
      - 'solutions/day03/**'
      - 'solutions/day04/**'
jobs:
  build-solution:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        directory: [ 'solutions/day01'
                   , 'solutions/day02'
                   , 'solutions/day03'
                   , 'solutions/day04'
                   ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: update stack
        run: stack upgrade
      - name: print stack version
        run: stack --version
      - name: build and run solution
        run: cd ${{ matrix.directory }} && stack build
