name: build-and-run-aoc-solution
on: 
  push:
    paths:
      - '.github/workflows/build_solution.yml'
      - 'solutions/day01/**'
      - 'solutions/day02/**'
      - 'solutions/day03/**'
  workflow_dispatch:
jobs:
  build-solution:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        directory: [ 'solutions/day01'
                   , 'solutions/day02'
                   , 'solutions/day03'
                   ]
    steps:
      - name: Debug Event Payload
        run: echo "Event payload: ${{ toJson(github.event) }}"
      - name: update stack
        run: stack upgrade
      - name: print stack version
        run: stack --version
      - name: checkout solutions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ matrix.directory  }}
      - name: build and run solution
        run: cd ${{ matrix.directory }} && stack build
