name: build-and-run-aoc-solution
on: push
jobs:
  build-and-run:
    runs-on: ubuntu-22.04
    steps:
      - name: update stack
        run: stack upgrade
      - name: print stack version
        run: stack --version
      - name: checkout solutions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            solutions
      - name: build and run solution
        run: cd solutions/day01 && stack build
